{% set name = "flux-core" %}
{% set version = "0.61.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-core/releases/download/v{{ version }}/flux-core-{{ version }}.tar.gz
  sha256: 06f38143723e3f8331f55893ad8f74d43eb0588078f91abb603690c3e5f5112c
  patches:
    - centos6.patch  # This patch can be removed once the conda-forge reference is updated

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('flux-core', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkgconfig
    - jq
  host:
    - python
    - zeromq
    - lz4-c
    - libarchive
    - lua
    - libhwloc
    - sqlite
    - cffi
    - jsonschema
    - aspell
    - valgrind
    - pyyaml
    - czmq
    - jansson
    - sphinx
    - ply
    - lua-luaposix
    - libuuid
    - ncurses
  run:
    - python
    - czmq
    - {{ mpi }}
    - cffi
    - ply
    - lua-luaposix
    - pyyaml
    - jsonschema

test:
  commands:
    - flux --help

about:
  home: https://flux-framework.org
  summary: core services for the Flux resource management framework
  description: |
    flux-core implements the lowest level services and interfaces for the
    Flux resource manager framework. It is intended to be the first 
    building block used in the construction of a site-composed Flux 
    resource manager.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://flux-framework.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - grondo
    - jan-janssen
