{% set name = "flux-core" %}
{% set version = "0.76.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-core/releases/download/v{{ version }}/flux-core-{{ version }}.tar.gz
  sha256: c28d271a50b4065c2399af844a51d2b0e7ab3fa262f4bbf15a4c1115cd6fe77c
  patches:
    - centos6.patch  # [build_platform != target_platform]
    - cross-compiling.patch  # [build_platform != target_platform]
    - disable-test-libeventlog-formatter.patch
    - disable-test-t0005-exec.patch
    - disable-test-t0013-config-file.patch
    - disable-test-t2406-job-exec-cleanup.patch
    - disable-test-t2500-job-attach.patch
    - disable-test-t2802-uri-cmd.patch
    - disable-test-python-t0002-wrapper.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('flux-core', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - automake =1.16
    - pkgconfig
    - jq
  host:
    - python
    - zeromq
    - lz4-c
    - libarchive
    - lua
    - libhwloc
    - sqlite
    - cffi
    - jsonschema
    - aspell
    - valgrind
    - pyyaml
    - czmq
    - jansson
    - setuptools
    - sphinx
    - ply
    - lua-luaposix
    - libuuid
    - ncurses
  run:
    - python
    - czmq
    - {{ mpi }}
    - cffi
    - ply
    - lua-luaposix
    - pyyaml
    - jsonschema

test:
  commands:
    - flux --help

about:
  home: https://flux-framework.org
  summary: core services for the Flux resource management framework
  description: |
    flux-core implements the lowest level services and interfaces for the
    Flux resource manager framework. It is intended to be the first 
    building block used in the construction of a site-composed Flux 
    resource manager.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://flux-framework.readthedocs.io/
  dev_url: https://github.com/flux-framework

extra:
  recipe-maintainers:
    - grondo
    - jan-janssen
